spring.profiles.active: 'production'
---
server:
  port: 8080
  servletPath: /
spring:
  neo4j:
    port: 7474
    host: 'graphdb'
  rabbitmq:
    port: 5672
    host: 'rabbit'
    username: guest
    password: guest
    listener:
      max-concurrency: 1
      prefetch: 1
      acknowledge-mode: auto
      auto-startup: true
    dynamic: true
  social:
    twitter:
      accessTokenSecret: 'gjxpdHcVwVT4G7aGBMz654DLHk1aVu1zBXVTohMifq2XU'
      accessToken: '922977192-jzCCOIHFYh8Fs9N5DjlxZfW6CxgtLzPZyohYuqTX'
      appSecret: 'pCmBTZ6dBqCaf1BTffkF8il0AAiWIhgUlYhhZ7jDZFMFuDyNa5'
      appId: 'bPIKaiR4d91amYlft7s6p39Nz'
  profiles: 'production'
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
---
server:
  port: 8080
  servletPath: /
spring:
  neo4j:
    port: 7474
    host: '192.168.99.100'
  rabbitmq:
    port: 5672
    host: 'localhost'
    username: guest
    password: guest
    listener:
      max-concurrency: 1
      prefetch: 1
      acknowledge-mode: auto
      auto-startup: true
    dynamic: true
  social:
    twitter:
      accessTokenSecret: 'gjxpdHcVwVT4G7aGBMz654DLHk1aVu1zBXVTohMifq2XU'
      accessToken: '922977192-jzCCOIHFYh8Fs9N5DjlxZfW6CxgtLzPZyohYuqTX'
      appSecret: 'pCmBTZ6dBqCaf1BTffkF8il0AAiWIhgUlYhhZ7jDZFMFuDyNa5'
      appId: 'bPIKaiR4d91amYlft7s6p39Nz'
  profiles: 'development'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
---
server:
  port: 8080
  servletPath: /
spring:
  neo4j:
    port: 7474
    host: '192.168.99.100'
  rabbitmq:
    port: 5672
    host: 'localhost'
    username: guest
    password: guest
    listener:
      max-concurrency: 1
      prefetch: 1
      acknowledge-mode: auto
      auto-startup: true
    dynamic: true
  social:
    twitter:
      accessTokenSecret: 'gjxpdHcVwVT4G7aGBMz654DLHk1aVu1zBXVTohMifq2XU'
      accessToken: '922977192-jzCCOIHFYh8Fs9N5DjlxZfW6CxgtLzPZyohYuqTX'
      appSecret: 'pCmBTZ6dBqCaf1BTffkF8il0AAiWIhgUlYhhZ7jDZFMFuDyNa5'
      appId: 'bPIKaiR4d91amYlft7s6p39Nz'
  profiles: 'test'
eureka:
  client:
    enabled: false